1 Write a Python Program to Add Two Matrices?

In [ ]:
import numpy as np

X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]

result = np.array(X) + np.array(Y)

print(result)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


2. Write a Python Program to Multiply Two Matrices?

In [ ]:
A = [[5, 4, 3],
         [2, 4, 6],
         [4, 7, 9]]
B = [[3, 2, 4],
         [4, 3, 6],
         [2, 7, 5]]

Result = [[sum(a * b for a, b in zip(Arow, Bcol))
                       for Bcol in zip(*B)]
                                for Arow in A]
# Printing multiplication result in the output
print("The multiplication result of matrix A and B is: ")
for res in Result:
    print(res)

The multiplication result of matrix A and B is: 
[37, 43, 59]
[34, 58, 62]
[58, 92, 103]


3. Write a Python Program to Transpose a Matrix?

In [ ]:
N = 4

def transpose(A):

 for i in range(N):
  for j in range(i+1, N):
   A[i][j], A[j][i] = A[j][i], A[i][j]


A = [ [1, 1, 1, 1],
 [2, 2, 2, 2],
 [3, 3, 3, 3],
 [4, 4, 4, 4]]

transpose(A)

print("Modified matrix is")
for i in range(N):
 for j in range(N):
  print(A[i][j], " ", end='')
 print()


Modified matrix is
1  2  3  4  
1  2  3  4  
1  2  3  4  
1  2  3  4  


4. Write a Python Program to Sort Words in Alphabetic Order?

In [ ]:
def F(S):
    W = S.split(" ")
    for i in range(len(W)):
        W[i] = W[i].lower()
    W.sort()

    return ' '.join(W)

S = "Vartika Arora"
print(F(S))

arora vartika


5. Write a Python Program to Remove Punctuation From a String?

In [ ]:
def remove_punctuation(test_str):

  result = ''.join(filter(lambda x: x.isalpha() or x.isdigit() or x.isspace(), test_str))
  return result

test_str = "ineuron, is best : for ! Data science ;"
print("The original string is : " + test_str)

result = remove_punctuation(test_str)
print("The string after punctuation filter : " + result)

The original string is : ineuron, is best : for ! Data science ;
The string after punctuation filter : ineuron is best  for  Data science 
